name: brains
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - kaggle
  - matplotlib
  - ipykernel
  - pyarrow
  - grip
  - ipywidgets
  - pytorch-cuda=12.1  # delete to install without CUDA
  - torchvision
  - pytorch
  - torchinfo
  - tensorboard
